(lang dune 3.19)

(using menhir 2.1)

(name veritas)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "William Gibbs")

(maintainers "William Gibbs")

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
